### ISSUE TITLE
Wrong import path in the book

### ISSUE THREAD

**Issue by ruliarmando** [shamahoque/mern-skeleton#1]
Hi, i bought your book, it is really good, but you have wrong import path in user.controller.js where errorHandler should be imported from '../helpers/dbErrorHandler' but in the book you imported it from './error.controller', although in this repo you correctly imported it. Thanks

**Comment by shamahoque** [comment]
Hey! Thank you for getting the book and also pointing out the mismatch. It is much appreciated.

The code repositories here on GitHub for the projects in the book are working versions. You can refer to these and also to the linked demos. 

If you face any issues or have any further queries, feel free to reach out here or email at [author@mernbook.com](author@mernbook.com)

**Comment by ruliarmando** [comment]
Ok then, noted and thanks again for the book
