### ISSUE TITLE
Runtime error - Error: Cannot find module '@babel/runtime/helpers/builtin/classCallCheck'

### ISSUE THREAD

**Issue by waditya** [shamahoque/mern-skeleton#2]
Hi team,
Whenever I run the npm run development command, I get below error. I am new to Node.js as well as the MERN stack. Could you please guide me?

E:\Project\MERN_SKELETON>npm run development

> mern_skeleton@1.0.0 development E:\Project\MERN_SKELETON
> nodemon

[nodemon] 1.18.3
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: E:\Project\MERN_SKELETON\server/**/*
[nodemon] starting `webpack --mode=development --config webpack.config.server.js && node ./dist/server.generated.js`
Hash: 76190224d85517e66d67
Version: webpack 4.16.4
Time: 1484ms
Built at: 2018-08-07 01:08:28
                               Asset     Size  Chunks             Chunk Names
1fc7d431ee87303939c51391c63b812e.jpg   53 KiB          [emitted]
                 server.generated.js  133 KiB    main  [emitted]  main
Entrypoint main = server.generated.js
[./client/MainRouter.js] 4.88 KiB {main} [built]
[./config/config.js] 981 bytes {main} [built]
[./server/express.js] 4.72 KiB {main} [built]
[./server/server.js] 807 bytes {main} [built]
[express] external "express" 42 bytes {main} [built]
[helmet] external "helmet" 42 bytes {main} [built]
[material-ui/colors] external "material-ui/colors" 42 bytes {main} [built]
[material-ui/styles] external "material-ui/styles" 42 bytes {main} [built]
[mongoose] external "mongoose" 42 bytes {main} [built]
[path] external "path" 42 bytes {main} [built]
[react] external "react" 42 bytes {main} [built]
[react-dom/server] external "react-dom/server" 42 bytes {main} [built]
[react-hot-loader] external "react-hot-loader" 42 bytes {main} [built]
[react-router-dom/StaticRouter] external "react-router-dom/StaticRouter" 42 bytes {main} [built]
[0] multi ./server/server.js 28 bytes {main} [built]
    + 56 hidden modules
**module.js:549
    throw err;
    ^**

**Error: Cannot find module '@babel/runtime/helpers/builtin/classCallCheck'**
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (E:\Project\MERN_SKELETON\node_modules\react-event-listener\dist\react-event-listener.cjs.js:7:39)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (E:\Project\MERN_SKELETON\node_modules\material-ui\Input\Textarea.js:52:27)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by shamahoque** [comment]
This seems to be an issue with Material-UI. I am assuming you are using a newer version than the one used for this code (1.0.0-beta.43). 

A possible simple fix to get the given code up and running for now: install this specific version of material-ui and then run the application.

`npm install  material-ui@1.0.0-beta.43`
`npm run development`

Let me know if the issue still persists.

**Comment by waditya** [comment]
@shamahoque  - Thank you. I tried it. It didn't solve the issue. Since it was an issue related it to 
I installed babel run time **(@babel/runtime/helpers)** with below command

**npm install --save-dev babel-plugin-transform-runtime**
**npm run development**

After doing this, the problem was solved.

**Comment by waditya** [comment]
I am closing this issue.
