### ISSUE TITLE
Main page not opening

### ISSUE THREAD

**Issue by ghost** [shamahoque/mern-skeleton#3]
Hey guys,

I cloned this repo, ran `npm i` and tried to start a project with `npm run development`. 
Everything looks fine, the project compiles and I got a message `Server started on port 3000.`
Great! But I see a blank loading page when I tried to open up http://localhost:3000 webpage. 

It's just infinitely loading. No logs/error messages in the server console. 
I also tried to get page with wget like: `wget http://localhost:3000` but no luck.

### Tab spinner:

![image](https://user-images.githubusercontent.com/12616843/63649892-111bfe80-c74c-11e9-8a62-ed983bb5d30f.png)

### The whole output from `npm run development` command:

![image](https://user-images.githubusercontent.com/12616843/63649840-7de2c900-c74b-11e9-85db-7c5b8bb6e720.png)

### Nmap also said port is open:

![image](https://user-images.githubusercontent.com/12616843/63649846-905d0280-c74b-11e9-949e-82273542fa34.png)

Any ideas? Thanks.

**Comment by rhill34** [comment]
Do you have Mongo running? The entire project is a MERN stack so you need to have Mongo installed and running also to the project.

**Comment by powderblock** [comment]
Can anyone please elaborate on what it means to have Mongo running and pointed to the Project? Mongo configured in config.js? Do I need to create the DB manually first? Any help is appreciated!
