### ISSUE TITLE
SSR components do not match the client side components

### ISSUE THREAD

**Issue by aaditkamat** [shamahoque/mern-skeleton#8]
I occasionally run into errors that look like this: 
1) https://stackoverflow.com/questions/45350360/react-16-warning-warning-js36-warning-did-not-expect-server-html-to-contain-a
2) https://stackoverflow.com/questions/55490802/react-hmr-with-ssr

From all the SO posts I have looked at, it seems like an issue with rehydrating the App upon hot reloading:
https://github.com/shamahoque/mern-skeleton/blob/1e28284d20c06ca8ab91b849797d323c76107e68/client/main.js#L5

**Comment by shamahoque** [comment]
Yes, this issue is related to hydration. As some of the SO answers indicate, you have to deal with these on a case-by-case basis. In some cases, it is expected the SSR component and client component will not match (could be due to auth considerations present in the frontend code).

**Comment by aaditkamat** [comment]
For development purposes would you suggest checking for hot reload to use either `render` or `hydrate` so that the mismatch does not make debugging harder?

**Comment by shamahoque** [comment]
You could do that but you risk missing out on new warnings that you should be handling and fixing.
